INSERT [dbo].[Countries] ([Id], [Name]) VALUES (1, N'Andorra')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (2, N'United Arab Emirates')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (3, N'Afghanistan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (4, N'Antigua and Barbuda')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (5, N'Anguilla')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (6, N'Albania')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (7, N'Armenia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (8, N'Netherlands Antilles')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (9, N'Angola')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (10, N'Argentina')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (11, N'Austria')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (12, N'Australia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (13, N'Aruba')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (14, N'Azerbaijan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (15, N'Bosnia and Herzegovina')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (16, N'Barbados')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (17, N'Bangladesh')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (18, N'Belgium')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (19, N'Burkina Faso')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (20, N'Bulgaria')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (21, N'Bahrain')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (22, N'Burundi')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (23, N'Benin')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (24, N'Bermuda')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (25, N'Brunei Darussalam')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (26, N'Bolivia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (27, N'Brazil')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (28, N'Bahamas')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (29, N'Bhutan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (30, N'Botswana')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (31, N'Belarus')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (32, N'Belize')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (33, N'Canada')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (34, N'Cocos (Keeling) Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (35, N'Democratic Republic of the Congo')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (36, N'Central African Republic')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (37, N'Congo')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (38, N'Switzerland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (39, N'Cote D''Ivoire (Ivory Coast)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (40, N'Cook Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (41, N'Chile')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (42, N'Cameroon')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (43, N'China')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (44, N'Colombia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (45, N'Costa Rica')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (46, N'Cuba')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (47, N'Cape Verde')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (48, N'Christmas Island')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (49, N'Cyprus')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (50, N'Czech Republic')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (51, N'Germany')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (52, N'Djibouti')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (53, N'Denmark')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (54, N'Dominica')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (55, N'Dominican Republic')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (56, N'Algeria')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (57, N'Ecuador')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (58, N'Estonia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (59, N'Egypt')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (60, N'Western Sahara')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (61, N'Eritrea')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (62, N'Spain')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (63, N'Ethiopia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (64, N'Finland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (65, N'Fiji')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (66, N'Falkland Islands (Malvinas)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (67, N'Federated States of Micronesia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (68, N'Faroe Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (69, N'France')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (70, N'Gabon')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (71, N'Great Britain (UK)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (72, N'Grenada')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (73, N'Georgia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (74, N'French Guiana')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (75, N'Guernsey')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (76, N'Ghana')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (77, N'Gibraltar')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (78, N'Greenland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (79, N'Gambia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (80, N'Guinea')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (81, N'Guadeloupe')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (82, N'Equatorial Guinea')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (83, N'Greece')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (84, N'S. Georgia and S. Sandwich Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (85, N'Guatemala')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (86, N'Guinea-Bissau')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (87, N'Guyana')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (88, N'Hong Kong')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (89, N'Honduras')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (90, N'Croatia (Hrvatska)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (91, N'Haiti')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (92, N'Hungary')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (93, N'Indonesia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (94, N'Ireland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (95, N'Israel')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (96, N'India')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (97, N'Iraq')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (98, N'Iran')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (99, N'Iceland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (100, N'Italy')
GO
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (101, N'Jamaica')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (102, N'Jordan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (103, N'Japan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (104, N'Kenya')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (105, N'Kyrgyzstan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (106, N'Cambodia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (107, N'Kiribati')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (108, N'Comoros')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (109, N'Saint Kitts and Nevis')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (110, N'Korea (North)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (111, N'Korea (South)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (112, N'Kuwait', N'KW')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (113, N'Cayman Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (114, N'Kazakhstan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (115, N'Laos')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (116, N'Lebanon')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (117, N'Saint Lucia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (118, N'Liechtenstein')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (119, N'Sri Lanka')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (120, N'Liberia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (121, N'Lesotho')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (122, N'Lithuania')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (123, N'Luxembourg')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (124, N'Latvia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (125, N'Libya')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (126, N'Morocco')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (127, N'Monaco')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (128, N'Moldova')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (129, N'Madagascar')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (130, N'Marshall Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (131, N'Macedonia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (132, N'Mali')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (133, N'Myanmar')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (134, N'Mongolia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (135, N'Macao')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (136, N'Northern Mariana Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (137, N'Martinique')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (138, N'Mauritania')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (139, N'Montserrat')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (140, N'Malta')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (141, N'Mauritius')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (142, N'Maldives')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (143, N'Malawi')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (144, N'Mexico')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (145, N'Malaysia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (146, N'Mozambique')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (147, N'Namibia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (148, N'New Caledonia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (149, N'Niger')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (150, N'Norfolk Island')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (151, N'Nigeria')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (152, N'Nicaragua')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (153, N'Netherlands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (154, N'Norway')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (155, N'Nepal')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (156, N'Nauru')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (157, N'Niue')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (158, N'New Zealand')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (159, N'Oman')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (160, N'Panama')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (161, N'Peru')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (162, N'French Polynesia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (163, N'Papua New Guinea')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (164, N'Philippines')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (165, N'Pakistan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (166, N'Poland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (167, N'Saint Pierre and Miquelon')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (168, N'Pitcairn')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (169, N'Palestinian Territory')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (170, N'Portugal')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (171, N'Palau')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (172, N'Paraguay')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (173, N'Qatar')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (174, N'Reunion')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (175, N'Romania')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (177, N'Rwanda')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (178, N'Saudi Arabia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (179, N'Solomon Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (180, N'Seychelles')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (181, N'Sudan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (182, N'Sweden')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (183, N'Singapore')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (184, N'Saint Helena')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (185, N'Slovenia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (186, N'Svalbard and Jan Mayen')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (187, N'Slovakia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (188, N'Sierra Leone')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (189, N'San Marino')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (190, N'Senegal')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (191, N'Somalia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (192, N'Suriname')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (193, N'Sao Tome and Principe')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (194, N'El Salvador')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (195, N'Syria')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (196, N'Swaziland')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (197, N'Turks and Caicos Islands')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (198, N'Chad')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (199, N'French Southern Territories')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (200, N'Togo')
GO
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (201, N'Thailand')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (202, N'Tajikistan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (203, N'Tokelau')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (204, N'Turkmenistan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (205, N'Tunisia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (206, N'Tonga')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (207, N'Turkey')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (208, N'Trinidad and Tobago')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (209, N'Tuvalu')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (210, N'Taiwan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (211, N'Tanzania')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (212, N'Ukraine')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (213, N'Uganda')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (214, N'Uruguay')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (215, N'Uzbekistan')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (216, N'Saint Vincent and the Grenadines')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (217, N'Venezuela')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (218, N'Virgin Islands (British)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (219, N'Virgin Islands (U.S.)')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (220, N'Viet Nam')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (221, N'Vanuatu')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (222, N'Wallis and Futuna')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (223, N'Samoa')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (224, N'Yemen')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (225, N'Mayotte')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (226, N'South Africa')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (227, N'Zambia')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (228, N'Zaire')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (229, N'Zimbabwe')
INSERT [dbo].[Countries] ([Id], [Name]) VALUES (230, N'United States of America')
